server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buyme_db
    username: junewoo
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
