name: BuyMe CI  # 워크플로우 이름

on:
  push:
    branches: [ main, develop ]  # main, develop 브랜치에 push 이벤트 발생 시 실행
  pull_request:
    branches: [ main, develop ]  # main, develop 브랜치로 PR 생성 시 실행

jobs:
  build_job:
    runs-on: ubuntu-latest  # 우분투 최신 버전 환경에서 실행

    services:
      postgres:
        image: postgres:17.5  # PostgreSQL 17.5 버전 도커 컨테이너 실행
        env:
          POSTGRES_USER: junewoo       # DB 사용자명
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  # DB 비밀번호 (실제값으로 변경 필요)
          POSTGRES_DB: buyme_db        # 생성할 DB 이름
        ports:
          - 5432:5432                  # 호스트와 컨테이너 포트 바인딩
        options: >-                   # 헬스체크 설정
          --health-cmd="pg_isready -U junewoo -d buyme_db"  # DB 준비 상태 확인 명령
          --health-interval=10s        # 10초마다 헬스체크 실행
          --health-timeout=5s          # 헬스체크 최대 대기 시간 5초
          --health-retries=5           # 헬스체크 실패 시 재시도 횟수 5번

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 리포지토리 소스 코드 체크아웃

      - name: Set up JDK 17.0.15
        uses: actions/setup-java@v4  # OpenJDK 17.0.15 설치
        with:
          java-version: '17.0.15'    # JDK 버전 지정
          distribution: 'temurin'    # Temurin (OpenJDK 배포판)

      - name: Gradle Caching
        uses: actions/cache@v3       # Gradle 빌드 캐시 저장/복원으로 빌드 속도 향상
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew        # gradlew 실행 권한 부여

      - name: Wait for PostgreSQL to start
        run: |
          for i in {1..10}; do       # 최대 10번까지 시도
            nc -z localhost 5432 && echo "Postgres is up!" && exit 0  # 5432 포트 열렸는지 체크
            echo "Waiting for Postgres..."
            sleep 3                  # 3초 대기 후 재시도
          done
          exit 1                     # 10번 실패 시 종료 코드 1 반환 (실패)

      - name: Build with Gradle
        run: ./gradlew build -x test  # 테스트 제외하고 Gradle 빌드 수행
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/buyme_db   # DB URL 환경 변수
          SPRING_DATASOURCE_USERNAME: junewoo                               # DB 사용자명 환경 변수
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}                          # DB 비밀번호 환경 변수
